# Generated by Django 4.1.3 on 2023-04-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField(default='')),
                ('composition', models.TextField(default='')),
                ('proadapp', models.TextField(default='')),
                ('catagory', models.CharField(choices=[('CR', 'PADS'), ('ML', 'SHAMPOOS'), ('LS', 'LASSIES'), ('MS', 'MILKSHAKE')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
