# Generated by Django 4.1.3 on 2023-05-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ec', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
